# Generated by Django 6.0.6 on 2026-07-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_razorpay_payment_id_order_refund_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
