# Generated by Django 6.0.6 on 2026-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_is_exclusive_product_prime_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
