# Generated by Django 4.2.30 on 2026-08-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_emailverificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
