# Generated by Django 4.2.30 on 2026-08-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_supportticket_subject'),
        ('store', '0019_load_products'),
    ]

    operations = [
    ]
